---
reviews:
  - name: "API Review Team"
    files:
      - api/
      - docs/api/*.md
    team: "@org/api-team"
  - name: "Bananas Fosters Team"
    files:
      - spec/
      - /*.yml
    team: "@org/banana-team"
