version: 2
jobs:
   build:
     docker:
       - image: circleci/node:9.5-browsers
     steps:
       - checkout
       - run: echo "hello world"
notify:
   webhooks:
      - url: https://check-checker.herokuapp.com/payload
